(define-module (bargyle bar))

(define (colour key)
  (case key
    ((#:default-fg) "#a7a5a5")
    ((#:default-bg) "#333232")
    ((#:monitor-fg) "#976e8b")
    ((#:monitor-bg) "#333232")
    ((#:focused-monitor-fg) "#d9d8d8")
    ((#:focused-monitor-bg) "#5d254c")
    ((#:free-fg) "#737171")
    ((#:free-bg) "#333232")
    ((#:focused-free-fg) "#000000")
    ((#:focused-free-bg) "#504e4e")
    ((#:occupied-fg) "#d9d8d8")
    ((#:occupied-bg) "#333232")
    ((#:focused-occupied-fg) "#ffffff")
    ((#:focused-occupied-bg) "#504e4e")
    ((#:urgent-fg) "#f15d66")
    ((#:urgent-bg) "#333232")
    ((#:focused-urgent-fg) "#501d1f")
    ((#:focused-urgent-bg) "#d5443e")
    ((#:state-fg) "#89b09c")
    ((#:state-bg) "#333232")
    ((#:title-fg) "#a8a2c0")
    ((#:title-bg) "#333232")
    ((#:sys-fg) "#b1a57d")
    ((#:sys-bg) "#333232")
    (else key)))

(define* (markup content #:key (fg #:default-fg) (bg #:default-bg) on-click)
  (let* ((fg (colour fg))
	 (bg (colour bg)))
    (if on-click
	(simple-format #f "%{F~a}%{B~a}%{A:~a:} ~a %{A}%{B-}%{F-}" fg bg on-click content)
	(simple-format #f "%{F~a}%{B~a} ~a %{B-}%{F-}" fg bg content))))

(define-public (make-mu e)
  (let ((name (substring e 1)))
    (lambda* (fg bg on-click-fmt #:rest fmt-exprs)
      (let ((exprs (if (null? fmt-exprs)
		       (list name)
		       fmt-exprs)))
	(markup name #:fg fg #:bg bg
		#:on-click (apply simple-format #f on-click-fmt exprs))))))

